[package]
name = "codeadvent"
version = "0.1.0"
authors = ["cavos <kkwiecinski@outlook.com>"]

[dependencies]
regex = "1"
lazy_static = "1.2.0"
multiarray = "0.1.3"
chrono = "0.4"
array-init = "0.0.4"